### ISSUE TITLE
请问一下Activitynet1.3数据集提取出的图片和光流大概多大？

### ISSUE THREAD

**Issue by Zhuysheng** [Line290/ActivityNet_task_1#1]

**Comment by Line290** [comment]
1T多还是2T多的

**Comment by Zhuysheng** [comment]
Thanks. I have several questions if you could help me.
1. How many days would it take to extract by myself? Is it possible to upload the extracted pictures and flows on Google cloud? 
2. How to generate the 16 list files?

**Comment by Line290** [comment]
Hi Zhuysheng，

1. I'm sorry to tell you the extracted data has been deleted. My teammate extracted it. In my memory, it took us several days(maybe one week) with 16~24 V100. 

2. 16 list files were generated by split the whole list file(train+val+test) simply. You can find how to generate 3 parts of list file in here:
https://github.com/Line290/ActivityNet_task_1/blob/master/ActivityNet_task_1_summary.pdf

**Comment by Zhuysheng** [comment]
@Line290 Mang thanks!
Since its too time consuming for me to extract images and flows with only one GPU card, is it convenient for you to provide the extracted features.

**Comment by Line290** [comment]
@Zhuysheng I uploaded the non-rescale feature in Baidu Drive. I updated the README, and you can find the shared link on it. If you want to use it to train BSN, you can rescale it by the script in here:
https://github.com/Line290/ActivityNet_task_1/blob/master/BSN/data_process.py
You need to do some adjustments to the script. 
Hope it will help you.

**Comment by Zhuysheng** [comment]
@Line290 Thanks, but how to decompress the zstd file,
I try: zstd -d dpn92_non_rescale_feats_both.zstd -o dpn92, and my output file is dpn92, I don't know how to read this file.
