### ISSUE TITLE
hi, may I know did you resize the image when do "Extract Frames and Optical Flow Images" use denseflow? If yes, resized to what size? thanks

### ISSUE THREAD

**Issue by semchan** [Line290/ActivityNet_task_1#5]

**Comment by Line290** [comment]
256*256

**Comment by semchan** [comment]
thanks

**Comment by semchan** [comment]
Did you crop the image when you resize to  keep the aspect ration (W /H) as same as the original image? thanks a lot.

**Comment by Line290** [comment]
Sorry for the wrong answer, it should be 340\*256(Width\*Height). We followed [this](https://github.com/yjxiong/temporal-segment-networks/blob/master/scripts/extract_optical_flow.sh) to process video.

**Comment by semchan** [comment]
thanks very much for your quick response

**Comment by semchan** [comment]
> Sorry for the wrong answer, it should be 340*256(Width*Height). We followed [this](https://github.com/yjxiong/temporal-segment-networks/blob/master/scripts/extract_optical_flow.sh) to process video.

I just some doubts that some videos is not always width lager than height, but height is lager than width indeed, I think it may not always suitable for all videos to resize to 340*256(Width*Height).
