### ISSUE TITLE
about pretrained tsn-flow model

### ISSUE THREAD

**Issue by shixiaotong1101** [Line290/ActivityNet_task_1#7]
i want to train the bsn with pretrained tsn,but i do not find the flow model,could you share it with me?

**Comment by Line290** [comment]
Hi @shixiaotong1101 , you can find the pretrained flow model on the bottom of README.md.

**Comment by shixiaotong1101** [comment]
yes, i can find the rgb model,but i want to use&nbsp;dpn92_flow__flow_model_best.pth.tar, where could i find it?

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Daquan Lin ***@***.***&gt;;
发送时间：2021年6月17日(星期四) 晚上6:22
收件人："Line290/ActivityNet_task_1" ***@***.***&gt;;
抄送："shixiaotong1101 ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [Line290/ActivityNet_task_1] about pretrained tsn-flow model (#7)
-----------------------------------

 

 
Hi @shixiaotong1101 , you can find the pretrained flow model on the bottom of README.md.

**Comment by shixiaotong1101** [comment]
yes, i can find the rgb model,but i want to use dpn92_flow__flow_model_best.pth.tar, where could i find it?

**Comment by Line290** [comment]
https://drive.google.com/open?id=1wHXeek6QCxb5irOMoOI7Q2sdjTaQoe1M

**Comment by shixiaotong1101** [comment]
oh！if i want to extract flow feature, i should fix the default model path and mode, thank you
